AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  RepositoryName:
    Type: String

Resources:
  CodeCommitRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Ref RepositoryName

Outputs:
  RepositoryName:
    Value: !Ref RepositoryName
    Export:
      Name: ReactViteSampleRepositoryName

  RepositoryArn:
    Value: !GetAtt CodeCommitRepository.Arn
    Export:
      Name: ReactViteSampleRepositoryArn
